"""
app/agent/nodes/diff_parser.py
───────────────────────────────
The DiffParserNode: parses a raw unified diff into structured DiffChunk objects.

This is the most important node to get right because every downstream node
depends on its output. Garbage in → garbage reviews out.

No LLM is involved here. This is pure deterministic Python, which means:
1. It's fast (microseconds, not seconds).
2. It's 100% testable without mocking anything.
3. It's the right place to enforce all filtering invariants once, rather
   than having each LLM node re-implement "skip lock files" logic.

Library choice: `unidiff`
  Parses unified diff format (the format git produces and GitHub returns
  from its API). It handles edge cases like binary files, mode changes,
  and renamed files that naive line-splitting would miss.

Chunking rationale:
  We chunk at the FILE boundary by default. A single file's diff becomes
  one DiffChunk. If a file's diff exceeds MAX_CHUNK_TOKENS, we further
  split at hunk boundaries (each @@ ... @@ block is a natural split point).
  This preserves maximum context while respecting LLM context windows.
  See: _chunk_large_file() for the splitting logic.
"""

from __future__ import annotations

import logging
import re
from pathlib import PurePosixPath
from typing import List, Optional, Set

from unidiff import PatchSet, PatchedFile

from app.agent.state import AgentState, DiffChunk

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Configuration constants
# ---------------------------------------------------------------------------

# Rough token budget per chunk sent to an LLM node.
# We use characters as a proxy (1 token ≈ 4 chars for code).
# 6000 tokens × 4 chars = 24,000 chars. We use 20,000 to be conservative
# and leave headroom for the system prompt and JSON response.
MAX_CHUNK_CHARS: int = 20_000

# File patterns to skip entirely. These files are either:
#   - Auto-generated (reviewing them is noise)
#   - Binary (can't review meaningfully)
#   - Lock files (huge diffs, zero security/logic value)
SKIP_FILENAME_PATTERNS: Set[str] = {
    "package-lock.json",
    "yarn.lock",
    "poetry.lock",
    "Pipfile.lock",
    "Cargo.lock",
    "composer.lock",
    "Gemfile.lock",
    "go.sum",
    "pnpm-lock.yaml",
    "uv.lock",
}

SKIP_EXTENSION_PATTERNS: Set[str] = {
    ".min.js",
    ".min.css",
    ".map",          # source maps
    ".pb",           # protobuf compiled
    ".pyc",
    ".pyo",
    ".class",        # Java bytecode
    ".jar",
    ".wasm",
    ".svg",          # usually generated/large
    ".png",
    ".jpg",
    ".jpeg",
    ".gif",
    ".ico",
    ".pdf",
    ".zip",
    ".tar",
    ".gz",
}

# Header patterns that indicate auto-generated files.
# We check the first 5 lines of the diff content for these.
AUTOGENERATED_MARKERS: List[str] = [
    "DO NOT EDIT",
    "do not edit",
    "Code generated",
    "AUTO-GENERATED",
    "autogenerated",
    "This file is automatically generated",
    "@generated",
]

# Map file extensions to language names for LLM context.
EXTENSION_TO_LANGUAGE: dict[str, str] = {
    ".py":    "python",
    ".js":    "javascript",
    ".ts":    "typescript",
    ".tsx":   "typescript",
    ".jsx":   "javascript",
    ".java":  "java",
    ".go":    "go",
    ".rs":    "rust",
    ".rb":    "ruby",
    ".php":   "php",
    ".cs":    "csharp",
    ".cpp":   "cpp",
    ".c":     "c",
    ".h":     "c",
    ".hpp":   "cpp",
    ".kt":    "kotlin",
    ".swift": "swift",
    ".sh":    "bash",
    ".yaml":  "yaml",
    ".yml":   "yaml",
    ".toml":  "toml",
    ".json":  "json",
    ".sql":   "sql",
    ".md":    "markdown",
    ".tf":    "terraform",
}


# ---------------------------------------------------------------------------
# Public node function
# ---------------------------------------------------------------------------

def run(state: AgentState) -> AgentState:
    """
    LangGraph node entry point.

    Reads:  state["raw_diff"]
    Writes: state["diff_chunks"]
            state["error"] (on failure, without raising)

    Returns a partial AgentState dict — LangGraph merges this into the
    full state. Only keys we touch are included in the return value.

    Design decision: we return on error without raising. This allows LangGraph
    to continue to the next node. Downstream nodes check `state["error"]` and
    skip their LLM calls if the parser failed, producing an empty review rather
    than a crashed pipeline. An empty review is recoverable; an exception is not.
    """
    raw_diff: str = state.get("raw_diff", "")

    if not raw_diff or not raw_diff.strip():
        logger.warning("DiffParserNode: received empty diff, nothing to parse")
        return {"diff_chunks": [], "error": None}  # type: ignore[return-value]

    try:
        chunks = parse_diff(raw_diff)
        logger.info(
            "DiffParserNode: parsed %d chunks from diff (%d chars)",
            len(chunks),
            len(raw_diff),
        )
        return {"diff_chunks": chunks}  # type: ignore[return-value]

    except Exception as exc:  # noqa: BLE001
        # Broad catch is intentional here. We don't know what malformed diffs
        # unidiff might encounter. Log the full exception, write to state.error,
        # and let the graph continue.
        logger.exception("DiffParserNode: failed to parse diff")
        return {  # type: ignore[return-value]
            "diff_chunks": [],
            "error": f"DiffParserNode failed: {type(exc).__name__}: {exc}",
        }


# ---------------------------------------------------------------------------
# Core parsing logic (public for direct testing)
# ---------------------------------------------------------------------------

def parse_diff(raw_diff: str) -> List[DiffChunk]:
    """
    Parse a unified diff string into a list of DiffChunk objects.

    This function is pure (no side effects, no I/O) and therefore directly
    unit-testable without any mocking.

    Args:
        raw_diff: A unified diff string, as returned by the GitHub API's
                  GET /repos/{owner}/{repo}/pulls/{pull_number} endpoint
                  with Accept: application/vnd.github.v3.diff header.

    Returns:
        List of DiffChunk objects, with skipped files filtered out.
        May be empty if all changed files were filtered (e.g. only lock files).
    """
    try:
        patch_set = PatchSet.from_string(raw_diff)
    except Exception as exc:
        raise ValueError(f"Failed to parse unified diff: {exc}") from exc

    chunks: List[DiffChunk] = []

    for patched_file in patch_set:
        if _should_skip_file(patched_file):
            logger.debug("DiffParserNode: skipping %s", patched_file.path)
            continue

        file_chunks = _file_to_chunks(patched_file)
        chunks.extend(file_chunks)

    return chunks


# ---------------------------------------------------------------------------
# File-level helpers
# ---------------------------------------------------------------------------

def _should_skip_file(patched_file: PatchedFile) -> bool:
    """
    Returns True if this file should be excluded from review.

    We skip:
    1. Binary files — unidiff marks these; there's nothing to review.
    2. Files matching SKIP_FILENAME_PATTERNS (lock files, etc.).
    3. Files matching SKIP_EXTENSION_PATTERNS (minified, compiled, etc.).
    4. Files whose diff content contains auto-generated markers.
    """
    if patched_file.is_binary_file:
        return True

    path = PurePosixPath(patched_file.path)

    # Check exact filename match (for files like "package-lock.json")
    if path.name in SKIP_FILENAME_PATTERNS:
        return True

    # Check extension match (handles ".min.js" as a two-part suffix)
    filename = path.name
    for ext_pattern in SKIP_EXTENSION_PATTERNS:
        if filename.endswith(ext_pattern):
            return True

    # Check for auto-generated markers in the diff content
    if _is_autogenerated(patched_file):
        return True

    return False


def _is_autogenerated(patched_file: PatchedFile) -> bool:
    """
    Detect auto-generated files by scanning the first 5 lines of added content
    for well-known generation markers.

    We only look at added lines (prefix "+") because those are the new content.
    We limit to the first 5 lines because generation headers always appear at
    the top of the file.
    """
    added_lines = [
        line.value
        for hunk in patched_file
        for line in hunk
        if line.is_added
    ][:5]

    combined = " ".join(added_lines)
    return any(marker in combined for marker in AUTOGENERATED_MARKERS)


def _detect_language(file_path: str) -> str:
    """
    Map a file path to a programming language name.
    Falls back to "unknown" for unrecognised extensions.

    We use PurePosixPath to correctly handle paths like "src/api/routes.py"
    across all operating systems.
    """
    suffix = PurePosixPath(file_path).suffix.lower()
    return EXTENSION_TO_LANGUAGE.get(suffix, "unknown")


# ---------------------------------------------------------------------------
# Chunking logic
# ---------------------------------------------------------------------------

def _file_to_chunks(patched_file: PatchedFile) -> List[DiffChunk]:
    """
    Convert a single patched file into one or more DiffChunks.

    Strategy:
    1. Build the full diff text for this file by joining all its hunks.
    2. If it fits within MAX_CHUNK_CHARS, return a single DiffChunk.
    3. If it's too large, split at hunk boundaries (each @@ block).

    Why hunk boundaries? A hunk is already a natural semantic unit —
    it represents a contiguous block of changes. Splitting between hunks
    preserves context better than splitting at arbitrary line counts.
    """
    file_path = patched_file.path
    language = _detect_language(file_path)

    # Collect all hunks as text blocks
    hunk_texts: List[tuple[str, int, int]] = []  # (text, start_line, end_line)

    for hunk in patched_file:
        hunk_text = _hunk_to_text(hunk)
        # hunk.target_start is the starting line in the new (post-diff) file
        start_line = hunk.target_start
        end_line = start_line + hunk.target_length - 1
        hunk_texts.append((hunk_text, start_line, end_line))

    if not hunk_texts:
        return []

    full_content = "\n".join(text for text, _, _ in hunk_texts)

    # Fast path: entire file fits in one chunk
    if len(full_content) <= MAX_CHUNK_CHARS:
        start_line = hunk_texts[0][1]
        end_line = hunk_texts[-1][2]
        return [
            DiffChunk(
                file_path=file_path,
                start_line=start_line,
                end_line=end_line,
                content=full_content,
                language=language,
                chunk_index=0,
            )
        ]

    # File is too large — split at hunk boundaries
    return _split_into_chunks(file_path, language, hunk_texts)


def _hunk_to_text(hunk) -> str:  # type: ignore[no-untyped-def]
    """
    Convert a unidiff Hunk object to a human-readable string.

    We preserve the @@ header line and all diff lines (+/-/ ).
    The LLM understands this format natively.
    """
    lines = [str(hunk.section_header) if hunk.section_header else ""]
    for line in hunk:
        lines.append(str(line))
    return "\n".join(lines)


def _split_into_chunks(
    file_path: str,
    language: str,
    hunk_texts: List[tuple[str, int, int]],
) -> List[DiffChunk]:
    """
    Group hunks into chunks that each stay under MAX_CHUNK_CHARS.

    This is a greedy bin-packing approach: keep adding hunks to the current
    chunk until adding the next hunk would exceed the limit, then start a
    new chunk.

    Edge case: a single hunk that exceeds MAX_CHUNK_CHARS on its own. We
    include it as its own chunk anyway — truncating would produce a malformed
    diff the LLM can't parse. The LLM context window is large enough (128K
    on qwen-2.5-coder) that this should be extremely rare.
    """
    chunks: List[DiffChunk] = []
    current_hunk_group: List[tuple[str, int, int]] = []
    current_size: int = 0
    chunk_index: int = 0

    for hunk_text, start_line, end_line in hunk_texts:
        hunk_size = len(hunk_text)

        would_overflow = (
            current_size + hunk_size > MAX_CHUNK_CHARS
            and current_hunk_group  # don't flush an empty group
        )

        if would_overflow:
            chunk = _build_chunk(
                file_path, language, chunk_index, current_hunk_group
            )
            chunks.append(chunk)
            chunk_index += 1
            current_hunk_group = []
            current_size = 0

        current_hunk_group.append((hunk_text, start_line, end_line))
        current_size += hunk_size

    # Flush the last group
    if current_hunk_group:
        chunk = _build_chunk(file_path, language, chunk_index, current_hunk_group)
        chunks.append(chunk)

    return chunks


def _build_chunk(
    file_path: str,
    language: str,
    chunk_index: int,
    hunk_group: List[tuple[str, int, int]],
) -> DiffChunk:
    """Build a DiffChunk from a group of consecutive hunks."""
    content = "\n\n".join(text for text, _, _ in hunk_group)
    start_line = hunk_group[0][1]
    end_line = hunk_group[-1][2]
    return DiffChunk(
        file_path=file_path,
        start_line=start_line,
        end_line=end_line,
        content=content,
        language=language,
        chunk_index=chunk_index,
    )
