"""
tests/unit/test_diff_parser.py
───────────────────────────────
Unit tests for the DiffParserNode.

Test philosophy applied here:
- Each test covers exactly ONE behaviour.
- Tests use REAL diff strings generated by git subprocess, or carefully
  hand-crafted strings whose @@ headers match the actual line counts.
  This matters because `unidiff` validates the hunk headers strictly —
  a wrong count raises UnidiffParseError. Using git to generate fixtures
  is the only reliable way to guarantee correct format.

Running:
    pytest tests/unit/test_diff_parser.py -v
"""

import os
import subprocess
import tempfile

import pytest

from app.agent.nodes.diff_parser import (
    MAX_CHUNK_CHARS,
    _detect_language,
    parse_diff,
    run,
)
from app.agent.state import DiffChunk, initial_state


# ---------------------------------------------------------------------------
# Diff generation helpers — use real git to produce valid unified diffs
# ---------------------------------------------------------------------------

def _make_git_diff(files_before: dict, files_after: dict) -> str:
    """
    Generate a real unified diff by running git in a temp directory.

    Args:
        files_before: {relative_path: content} for the initial commit
        files_after:  {relative_path: content} for the modified state

    Returns:
        A valid unified diff string matching git's exact output format.
    """
    with tempfile.TemporaryDirectory() as d:
        subprocess.run(['git', 'init', '-q'], cwd=d, check=True)
        subprocess.run(['git', 'config', 'user.email', 't@t.com'], cwd=d, check=True)
        subprocess.run(['git', 'config', 'user.name', 'T'], cwd=d, check=True)

        # Write and commit initial state
        for path, content in files_before.items():
            full_path = os.path.join(d, path)
            os.makedirs(os.path.dirname(full_path), exist_ok=True)
            with open(full_path, 'w') as f:
                f.write(content)

        subprocess.run(['git', 'add', '.'], cwd=d, check=True)
        subprocess.run(['git', 'commit', '-qm', 'init'], cwd=d, check=True)

        # Write modified state (don't commit — diff against working tree)
        for path, content in files_after.items():
            full_path = os.path.join(d, path)
            os.makedirs(os.path.dirname(full_path), exist_ok=True)
            with open(full_path, 'w') as f:
                f.write(content)

        result = subprocess.run(
            ['git', 'diff'],
            cwd=d,
            capture_output=True,
            text=True,
            check=True,
        )
        return result.stdout


# ---------------------------------------------------------------------------
# Fixtures — real diffs produced by git
# ---------------------------------------------------------------------------

@pytest.fixture
def simple_python_diff() -> str:
    return _make_git_diff(
        files_before={
            'src/api/routes.py': (
                'from fastapi import APIRouter\n\nrouter = APIRouter()\n\n'
                '@router.get("/health")\nasync def health_check():\n    return {"status": "ok"}\n'
            )
        },
        files_after={
            'src/api/routes.py': (
                'from fastapi import APIRouter\n\nrouter = APIRouter()\n\n'
                '@router.post("/users")\nasync def create_user(name: str, email: str):\n'
                '    user_id = 1\n    return {"id": user_id}\n\n'
                '@router.get("/health")\nasync def health_check():\n    return {"status": "ok"}\n'
            )
        },
    )


@pytest.fixture
def package_lock_diff() -> str:
    return _make_git_diff(
        files_before={'package-lock.json': '{\n  "lockfileVersion": 2,\n  "packages": {}\n}\n'},
        files_after={'package-lock.json': '{\n  "lockfileVersion": 3,\n  "packages": {}\n}\n'},
    )


@pytest.fixture
def multi_file_diff() -> str:
    return _make_git_diff(
        files_before={
            'src/auth.py': 'import hashlib\n\ndef hash_password(pw: str) -> str:\n    return hashlib.sha256(pw.encode()).hexdigest()\n',
            'src/models.py': 'class Session:\n    pass\n',
            'yarn.lock': 'lodash@4.17.20:\n  resolved "https://example.com"\n',
        },
        files_after={
            'src/auth.py': 'import hashlib\n\ndef verify_token(token: str) -> bool:\n    return True\n\ndef hash_password(pw: str) -> str:\n    return hashlib.sha256(pw.encode()).hexdigest()\n',
            'src/models.py': 'from dataclasses import dataclass\n\n@dataclass\nclass User:\n    id: int\n    email: str\n\nclass Session:\n    pass\n',
            'yarn.lock': 'lodash@4.17.21:\n  resolved "https://example.com"\n',
        },
    )


@pytest.fixture
def autogenerated_diff() -> str:
    return _make_git_diff(
        files_before={
            'src/generated/schema.py': '# Generated schema\n\nclass OldMessage:\n    pass\n',
        },
        files_after={
            'src/generated/schema.py': (
                '# DO NOT EDIT: This file is automatically generated by protoc\n'
                '# Generated schema\n\nclass OldMessage:\n    pass\n\nclass NewMessage:\n    pass\n'
            ),
        },
    )


@pytest.fixture
def mixed_files_diff() -> str:
    return _make_git_diff(
        files_before={
            'backend/auth.py': 'def login():\n    pass\n',
            'frontend/api.ts': 'export const API_URL = "https://api.example.com";\n',
            'proto/generated/user_pb2.py': '# -*- coding: utf-8 -*-\n\nDESCRIPTOR = None\n',
            'yarn.lock': 'lodash@4.17.20:\n  resolved "https://example.com"\n',
        },
        files_after={
            'backend/auth.py': (
                'import jwt\n\n'
                'def decode_token(token):\n    return jwt.decode(token, options={"verify_signature": False})\n\n'
                'def login():\n    pass\n'
            ),
            'frontend/api.ts': (
                'export async function fetchUser(id: string) {\n'
                '  const res = await fetch(`/api/users/${id}`);\n'
                '  return res.json();\n'
                '}\n\n'
                'export const API_URL = "https://api.example.com";\n'
            ),
            'proto/generated/user_pb2.py': (
                '# DO NOT EDIT: Generated by protoc\n'
                '# -*- coding: utf-8 -*-\n\nDESCRIPTOR = None\n'
            ),
            'yarn.lock': 'lodash@4.17.21:\n  resolved "https://example.com"\n',
        },
    )


# ---------------------------------------------------------------------------
# Tests: parse_diff() — the core function
# ---------------------------------------------------------------------------

class TestParseDiff:

    def test_returns_empty_list_when_diff_is_empty(self):
        result = parse_diff("")
        assert result == []

    def test_parses_single_python_file(self, simple_python_diff):
        chunks = parse_diff(simple_python_diff)

        assert len(chunks) == 1
        chunk = chunks[0]
        assert chunk.file_path == "src/api/routes.py"
        assert chunk.language == "python"
        assert chunk.chunk_index == 0

    def test_chunk_contains_diff_content(self, simple_python_diff):
        chunks = parse_diff(simple_python_diff)
        content = chunks[0].content
        assert "create_user" in content

    def test_filters_out_lock_file(self, package_lock_diff):
        chunks = parse_diff(package_lock_diff)
        assert chunks == [], "package-lock.json should be filtered entirely"

    def test_filters_lock_file_but_keeps_python_files(self, multi_file_diff):
        chunks = parse_diff(multi_file_diff)
        file_paths = {c.file_path for c in chunks}
        assert "src/auth.py" in file_paths
        assert "src/models.py" in file_paths
        assert "yarn.lock" not in file_paths, "yarn.lock must be filtered"

    def test_filters_autogenerated_file(self, autogenerated_diff):
        chunks = parse_diff(autogenerated_diff)
        assert chunks == [], "DO NOT EDIT files should be filtered"

    def test_chunk_line_numbers_are_non_negative(self, simple_python_diff):
        chunks = parse_diff(simple_python_diff)
        for chunk in chunks:
            assert chunk.start_line >= 0
            assert chunk.end_line >= chunk.start_line

    def test_multi_file_produces_multiple_chunks(self, multi_file_diff):
        chunks = parse_diff(multi_file_diff)
        # auth.py and models.py — yarn.lock filtered
        assert len(chunks) == 2

    def test_invalid_input_handled_gracefully(self):
        """Garbage that unidiff can't parse should raise or return empty — never crash."""
        try:
            result = parse_diff("this is not a diff at all")
            assert isinstance(result, list)
        except (ValueError, Exception):
            pass  # raising is also acceptable


# ---------------------------------------------------------------------------
# Tests: run() — the LangGraph node wrapper
# ---------------------------------------------------------------------------

class TestRunNode:

    def test_run_returns_diff_chunks_key(self, simple_python_diff):
        state = initial_state(
            raw_diff=simple_python_diff,
            repo_full_name="ayushkaul/test-repo",
            pr_number=1,
            head_sha="abc123",
        )
        result = run(state)
        assert "diff_chunks" in result
        assert isinstance(result["diff_chunks"], list)

    def test_run_does_not_set_error_on_success(self, simple_python_diff):
        state = initial_state(
            raw_diff=simple_python_diff,
            repo_full_name="ayushkaul/test-repo",
            pr_number=1,
            head_sha="abc123",
        )
        result = run(state)
        assert result.get("error") is None

    def test_run_returns_empty_chunks_for_empty_diff(self):
        state = initial_state(
            raw_diff="",
            repo_full_name="ayushkaul/test-repo",
            pr_number=1,
            head_sha="abc123",
        )
        result = run(state)
        assert result["diff_chunks"] == []
        assert result.get("error") is None

    def test_run_does_not_raise_on_any_input(self):
        """
        Fuzz test: run() must never raise regardless of input.
        LangGraph nodes that raise will crash the entire pipeline.
        """
        bad_inputs = [None, "", "   ", "not a diff", "--- /dev/null\n+++ /dev/null\n"]
        for bad_input in bad_inputs:
            state = initial_state(
                raw_diff=bad_input or "",
                repo_full_name="test/repo",
                pr_number=1,
                head_sha="000",
            )
            try:
                result = run(state)
                assert "diff_chunks" in result
            except Exception as exc:
                pytest.fail(
                    f"run() raised {type(exc).__name__} for input {bad_input!r}: {exc}"
                )

    def test_run_populates_chunks_correctly(self, multi_file_diff):
        state = initial_state(
            raw_diff=multi_file_diff,
            repo_full_name="ayushkaul/test-repo",
            pr_number=5,
            head_sha="deadbeef",
        )
        result = run(state)
        assert len(result["diff_chunks"]) == 2
        for chunk in result["diff_chunks"]:
            assert isinstance(chunk, DiffChunk)
            assert chunk.language == "python"


# ---------------------------------------------------------------------------
# Tests: _detect_language()
# ---------------------------------------------------------------------------

class TestDetectLanguage:

    @pytest.mark.parametrize("path,expected", [
        ("src/api/routes.py",           "python"),
        ("frontend/app.tsx",            "typescript"),
        ("frontend/index.js",           "javascript"),
        ("server/Main.java",            "java"),
        ("services/auth.go",            "go"),
        ("src/lib.rs",                  "rust"),
        ("deploy/main.tf",              "terraform"),
        ("config/database.yml",         "yaml"),
        ("queries/create_user.sql",     "sql"),
        ("README.md",                   "markdown"),
        ("src/unknown.xyz",             "unknown"),
        ("Makefile",                    "unknown"),
        ("deep/nested/path/file.ts",    "typescript"),
    ])
    def test_detects_language_from_extension(self, path, expected):
        assert _detect_language(path) == expected


# ---------------------------------------------------------------------------
# Tests: DiffChunk properties
# ---------------------------------------------------------------------------

class TestDiffChunkProperties:

    def test_line_count_is_correct(self):
        chunk = DiffChunk(
            file_path="src/api.py",
            start_line=10,
            end_line=20,
            content="+ some change",
            language="python",
        )
        assert chunk.line_count == 11  # 10 to 20 inclusive = 11 lines

    def test_dedup_key_format(self):
        chunk = DiffChunk(
            file_path="src/api.py",
            start_line=1,
            end_line=5,
            content="+ change",
            language="python",
            chunk_index=2,
        )
        assert chunk.dedup_key == "src/api.py:2"

    def test_path_normalises_backslashes(self):
        chunk = DiffChunk(
            file_path="src\\api\\routes.py",
            start_line=1,
            end_line=1,
            content="+line",
            language="python",
        )
        assert chunk.file_path == "src/api/routes.py"
        assert "\\" not in chunk.file_path

    def test_raises_on_negative_start_line(self):
        with pytest.raises(ValueError, match="start_line must be >= 0"):
            DiffChunk(
                file_path="src/api.py",
                start_line=-1,
                end_line=10,
                content="+line",
                language="python",
            )

    def test_raises_when_end_before_start(self):
        with pytest.raises(ValueError, match="end_line"):
            DiffChunk(
                file_path="src/api.py",
                start_line=10,
                end_line=5,
                content="+line",
                language="python",
            )


# ---------------------------------------------------------------------------
# Tests: Chunking behaviour for large files
# ---------------------------------------------------------------------------

class TestChunking:

    def _make_large_file_diff(self, num_lines_before: int, num_lines_after: int) -> str:
        """
        Generate a valid diff with precise line counts using real git.
        """
        before = "".join(f"line_{i} = {i}\n" for i in range(num_lines_before))
        after = "".join(f"line_{i} = {i}\n" for i in range(num_lines_after))
        return _make_git_diff(
            files_before={"src/large_file.py": before},
            files_after={"src/large_file.py": after},
        )

    def test_small_file_produces_single_chunk(self):
        diff = self._make_large_file_diff(num_lines_before=3, num_lines_after=50)
        chunks = parse_diff(diff)
        assert len(chunks) == 1
        assert chunks[0].file_path == "src/large_file.py"

    def test_chunk_has_correct_file_path(self):
        diff = self._make_large_file_diff(num_lines_before=3, num_lines_after=50)
        chunks = parse_diff(diff)
        for chunk in chunks:
            assert chunk.file_path == "src/large_file.py"

    def test_chunk_start_line_is_positive(self):
        diff = self._make_large_file_diff(num_lines_before=3, num_lines_after=50)
        chunks = parse_diff(diff)
        for chunk in chunks:
            assert chunk.start_line >= 0
            assert chunk.end_line >= chunk.start_line

    def test_chunk_indices_are_sequential(self):
        """
        When a file produces multiple chunks, chunk_index must be 0, 1, 2...
        """
        diff = self._make_large_file_diff(num_lines_before=3, num_lines_after=50)
        chunks = parse_diff(diff)

        from collections import defaultdict
        by_file: dict = defaultdict(list)
        for chunk in chunks:
            by_file[chunk.file_path].append(chunk)

        for file_chunks in by_file.values():
            indices = sorted(c.chunk_index for c in file_chunks)
            expected = list(range(len(indices)))
            assert indices == expected, f"Non-sequential chunk indices: {indices}"


# ---------------------------------------------------------------------------
# Integration: real-world mixed-file PR scenario
# ---------------------------------------------------------------------------

class TestRealWorldScenario:

    def test_pr_with_mixed_files_filters_correctly(self, mixed_files_diff):
        chunks = parse_diff(mixed_files_diff)
        reviewed_paths = {c.file_path for c in chunks}

        assert "backend/auth.py" in reviewed_paths
        assert "frontend/api.ts" in reviewed_paths
        assert "proto/generated/user_pb2.py" not in reviewed_paths
        assert "yarn.lock" not in reviewed_paths

    def test_chunk_languages_are_correctly_detected(self, mixed_files_diff):
        chunks = parse_diff(mixed_files_diff)
        lang_by_path = {c.file_path: c.language for c in chunks}

        assert lang_by_path["backend/auth.py"] == "python"
        assert lang_by_path["frontend/api.ts"] == "typescript"

    def test_full_pipeline_produces_valid_chunk_objects(self, mixed_files_diff):
        state = initial_state(
            raw_diff=mixed_files_diff,
            repo_full_name="ayushkaul/devmind",
            pr_number=7,
            head_sha="cafebabe",
        )
        result = run(state)

        assert result.get("error") is None
        for chunk in result["diff_chunks"]:
            assert isinstance(chunk, DiffChunk)
            assert chunk.file_path
            assert chunk.language
            assert chunk.content
            assert chunk.end_line >= chunk.start_line
